### ISSUE TITLE
Form Customization - can't hide TV

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#10865]
bobray created Redmine issue ID 10865

Form Customization rules to hide TVs aren't working for me any more. They were before.

**Comment by splittingred** [comment]
splittingred submitted:

I have no problem hiding TVs...whats your FC rule look like?

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r6450

**Comment by BobRay** [comment]
bobray submitted:

I just can't get this to work. Action: core/resource/update (as per docs)
also tried: core/resource/tvs Containing panel: blank
also tried: modx-panel-resource (as per docs) Name: tv4 (ID of the TV is 4) Rule: tvVisible Value: 0 The TV still shows for everyone after clearing and flushing everything in both FF and Chrome. It's my only FC rule.
