### ISSUE TITLE
Change "Workspaces" to "Package Installer" on tools menu?

### ISSUE THREAD

**Issue by BobRay** [modxbot/migrate#2106]
bobray created Redmine issue ID 2106

I don't really know where "Workspaces" is going so this may be a bad idea &#8211; but I'm suggesting that, for now at least, this makes sense since it's all you can do from that menu choice. The screen title should also be changes from "Packages" to "Package Installer" to match the menu. Also, when "workspaces" is implemented, it may deserve its own menu line. An alternative would be to have a "Package Management" menu choice that would lead to a screen with "Build Package," "Search for Packages," and "Install Package" tabs. Personally, I like "Package Builder" and "Package Installer" as separate menu choices since it's less confusing for new users.

**Comment by splittingred** [comment]
splittingred submitted:

I think we'll keep it at Workspaces for now to differentiate from Package Builder, and because Workspaces will eventually be 'multiple' (ie, more than one workspace). Keep this open for discussion, though.

**Comment by opengeek** [comment]
opengeek submitted:

I think this is an educational issue that could use some clarification by adding Core to the term, thus, Core Workspace. A workspace represents a functional core with a specific version and potentially various Core Extensions installed. This is similar to Eclipse workspaces that are essentially a way to create alternate configurations of an entire core for testing, upgrades, or other purposes.

**Comment by BobRay** [comment]
bobray submitted:

I think "Core Workspace" is a definite improvement, but there's a lot of potential for confusion with multiple contexts, multiple workspaces, and multiple cores. The more we can do to clarify it in the UI, the better. As a user, I would assume that switching to work on another core would involve switching the whole Manager to that core. I would expect to to see that choice at a pretty high level in the menu system, not down in "Workspaces" (e.g. Site | Switch to Core). If working on a core in "Workspaces" is just "editing", rather than switching the Manager to that core, I think it will create more confusion than it's worth. People can select a core in Workspaces, then go to "System Settings" and think they're making changes to a dfferent core than they really are. If Workspace is just the spot for managing the currently selected core, then things are kind of upside down, IMO, since things like setting system settings, roles, and permissions, should be done in the workspace. Maybe "Workspace" is specifically for physically changing the current core (as opposed to configuring it). If so, maybe there's a way to make that distinction clearer in the menu beyond just calling it "core workspace." One thing that would help clarify this discussion is to know what else will be happening in Workspace besides package stuff. I'm definitely confused here, but perhaps my confusion can help clarify what new users will experience.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed in r4301. Changed to 'Package Management'.

**Comment by BobRay** [comment]
bobray submitted:

Shaun, I updated to r4301 and reloaded the lexicon. I saw the change in the console but no change in the tools menu. Then I did a build and upgrade install & cleared the browser cache, but I still see "Workspaces" in the tools menu.
