### ISSUE TITLE
Policy Templates permissions drop-down failure

### ISSUE THREAD

**Issue by ghost** [modxbot/migrate#6380]
sottwell created Redmine issue ID 6380

The permissions drop-down list only displays from "about" to "delete_category", the AJAX that is supposed to load the options on demand isn't working. This is happening in every version of 2.2 I could get my hands on. 

2.1 works just fine.

**Comment by splittingred** [comment]
splittingred submitted:

Fixed earlier this AM: https://github.com/modxcms/revolution/commit/dc8d0c32a6c5be12cab84dea02db29ccbb2e1c8c

**Comment by ghost** [comment]
sottwell submitted:

Still doesn't work.

**Comment by splittingred** [comment]
splittingred submitted:

Definitely works for me. Refresh your browser cache.

**Comment by ghost** [comment]
sottwell submitted:

I'm sorry, I've completely cleared every cache and cookie on the browser, just now installed a fresh 2.2 rc2 in a different location, and it still doesn't work. Tried it on a remote host. Still doesn't work.

**Comment by ghost** [comment]
sottwell submitted:

My most abject apologies. I did not notice that it uses a paging menu instead of automatically loading the options as you scroll. Thanks to Jared Loman who gently pointed that out to me.
